version: "3"
services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            PHP_IDE_CONFIG: serverName=Docker
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php

    mysql:
        container_name: mysql
        image: mysql:docker-compose exec php bash
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASS}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/:/etc/mysql/
