<?php

namespace App\Enum;

class Parsers
{
    public const VIRTUAL_PARSERS = [
        'acxiom.com',
        'altisource.com',
        'analytics-iq.com',
        'aslmarketing.com',
        'assurance.com',
        'avrickdirect.com',
        'blockshopper.com',
        'businessprofiles.com',
        'cellphoneregistry.com',
        'courtregistry.org',
        'cupidscreen.com',
        'databaseusa.com',
        'datastreamgroup.com',
        'dataxltd.com',
        'deathrecords.org',
        'digitalmediasolutions.com',
        'fi.deluxe.com',
        'firstorion.com',
        'forewarn.com',
        'freebackgroundcheck.us',
        'freecellsearch.com',
        'governmentregistry.org',
        'govregistry.us',
        'ididata.com',
        'ihsmarkit.com',
        'incheck.net',
        'info.persopo.com',
        'infocore.com',
        'infutor.com',
        'instantbackgroundreport.com',
        'intelregistry.com',
        'kw1.knowwho.com',
        'lead.co',
        'mapsmoji.com',
        'mchdata.com',
        'members.infotracer.com',
        'modernize.com',
        'path2response.com',
        'peopleaz.org',
        'peopleconnect.us',
        'peoplelookup.com',
        'plusaddress.com',
        'publicrecords.onlinesearches.com',
        'publicrecordschecks.com',
        'publicrecordssearchonline.org',
        'recordsauthority.com',
        'revealmobile.com',
        'reversenumberdatabase.com',
        'reverserecords.org',
        'risk.lexisnexis.com',
        'ruf.com',
        'secure.publicrecords.com',
        'segment.com',
        'socialcatfish.com',
        'sortedbybirthdate.com',
        'sortedbyname.com',
        'strategicinfo.com',
        'studentclearinghouse.org',
        'thatsthem.com',
        'us.epsilon.com',
        'v2.parasolleads.com',
        'v12data.com',
        'webbula.com',
        'whitepages.plus',
        'wiland.com',
        'www.411.com',
        'www.700credit.com',
        'www.accudata.com',
        'www.addresssearch.com',
        'www.advancedbackgroundchecks.com',
        'www.advantagesolutions.net',
        'www.advcredit.com',
        'www.alc.com',
        'www.allareacodes.com',
        'www.allwebleads.com',
        'www.amrent.com',
        'www.ancestry.com',
        'www.background-check-only.com',
        'www.background-checks-systems.com',
        'www.backgroundchecks.com',
        'www.backgroundsonline.com',
        'www.beenverified.com',
        'www.belardiwong.com',
        'www.bisi.com',
        'www.blackbaud.com',
        'www.blackknightinc.com',
        'www.bridgevine.com',
        'www.cbcinnovis.com',
        'www.cdkglobal.com',
        'www.census-info.us',
        'www.ciccredit.com',
        'www.cicreports.com',
        'www.civisanalytics.com',
        'www.clarityservices.com',
        'www.compactlists.com',
        'www.corelogic.com',
        'www.corporationwiki.com',
        'www.cortera.com',
        'www.courtrecords.org',
        'www.criminalbackgroundrecords.com',
        'www.criminalpages.com',
        'www.criminalscreen.com',
        'www.criminalwatchdog.com',
        'www.dataamerica.com',
        'www.datafacts.com',
        'www.datatree.com',
        'www.dataverify.com',
        'www.detectiveunlimited.com',
        'www.divorcerecords.org',
        'www.earlywarning.com',
        'www.easybackgrounds.com',
        'www.edvisors.com',
        'www.emailtracer.com',
        'www.enformion.com',
        'www.equifax.com',
        'www.experian.com',
        'www.factualdata.com',
        'www.firstdirectmarketing.com',
        'www.fullcontact.com',
        'www.fusedleads.com',
        'www.goodhire.com',
        'www.govarrestrecords.org',
        'www.healthcare.com',
        'www.hireright.com',
        'www.home.neustar',
        'www.i-360.com',
        'www.idanalytics.com',
        'www.inflection.com',
        'www.infogroup.com',
        'www.infopay.com',
        'www.instantcheckmate.com',
        'www.instantpeoplefinder.com',
        'www.inteligator.com',
        'www.intellicorp.net',
        'www.kbmg.com',
        'www.kgbpeople.com',
        'www.lciinc.com',
        'www.libertydata.net',
        'www.locatefamily.com',
        'www.marriagerecords.org',
        'www.mocavo.com',
        'www.myyp.com',
        'www.nationalbackgroundcheck.com',
        'www.nctue.com',
        'www.openonline.com',
        'www.oracle.com',
        'www.owneriq.com',
        'www.partnerscredit.com',
        'www.peekyou.com',
        'www.peoplebyname.com',
        'www.peopleconnect.us',
        'www.peoplefinderonline.net',
        'www.peopleg2.com',
        'www.peoplesmart.com',
        'www.phonebooks.com',
        'www.phoneregistry.com',
        'www.pipl.com',
        'www.possiblenow.com',
        'www.public-record-site.com',
        'www.publicarrestrecords.org',
        'www.refinitiv.com',
        'www.reversegenie.com',
        'www.reversemobile.com',
        'www.reversephonelookup.com',
        'www.sagestreamllc.com',
        'www.searchbug.com',
        'www.skipsmasher.com',
        'www.snoopstation.com',
        'www.speedeondata.com',
        'www.spokeo.com',
        'www.spydialer.com',
        'www.staterecords.org',
        'www.sterlingcheck.com',
        'www.superpages.com',
        'www.tenantdetective.com',
        'www.theworknumber.com',
        'www.thomsonreuters.com',
        'www.tlo.com',
        'www.towerdata.com',
        'www.tracersinfoonline.com',
        'www.transunion.com',
        'www.truedata.co',
        'www.truthfinder.com',
        'www.ucc411.com',
        'www.valassis.com',
        'www.verisk.com',
        'www.viantinc.com',
        'www.voterfactory.com',
        'www.whitepages.com',
        'www.whoodle.com',
        'www.yasni.com',
        'www.ypstate.com',
        'www.zoominfo.com',
    ];

    public const PARSERS = [
        [// cloudflare, but works
            'name' => '411.com',
            'path' => 'src/Parser/411.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'abcheck.com',
            'path' => 'src/Parser/abcheck.js',
            'path_to_deleter' => '',
        ],
//        [// cloudflare
//            'name' => 'addresses.com',
//            'path' => 'src/Parser/addresses.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'americaphonebook.com',
            'path' => 'src/Parser/americaphonebook.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'anywho.com',
            'path' => 'src/Parser/anywho.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'backgroundalert.com',
            'path' => 'src/Parser/backgroundalert.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'backgroundcheck-run.com',
            'path' => 'src/Parser/backgroundcheck-run.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'beenverified.com',
            'path' => 'src/Parser/beenverified.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'clustrmaps.com',
            'path' => 'src/Parser/clustrmaps.js',
            'path_to_deleter' => '',
        ],
        [// cloudflare, but works
            'name' => 'cyberBackgroundChecks.com',
            'path' => 'src/Parser/cyberbackgroundchecks.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'emailtracer.com',
            'path' => 'src/Parser/emailtracer.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'familytreenow.com',
            'path' => 'src/Parser/familytreenow.js',
            'path_to_deleter' => '',
        ],
//        [// not working, waiting for selector failed
//            'name' => 'fastpeoplesearch.com',
//            'path' => 'src/Parser/fastpeoplesearch.js',
//            'path_to_deleter' => '',
//        ],
        [// cloudflare, but works
            'name' => 'findpeoplefast.com',
            'path' => 'src/Parser/findpeoplefast.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'findpeoplesearch.com',
            'path' => 'src/Parser/findpeoplesearch.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'firearmscalifornia.com',
            'path' => 'src/Parser/firearmscalifornia.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'floridaresidentsdirectory.com',
            'path' => 'src/Parser/floridaresidentsdirectory.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'freepeopledirectory.com',
            'path' => 'src/Parser/freepeopledirectory.js',
            'path_to_deleter' => '',
        ],
//        [// prompts you to enter an email address to send your results
//            'name' => 'governmentregistry.com',
//            'path' => 'src/Parser/governmentregistry.js',
//            'path_to_deleter' => '',
//        ],
//        [// not working, waiting for selector failed
//            'name' => 'persontrust.com',
//            'path' => 'src/Parser/persontrust.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'instantcheckmate.com',
            'path' => 'src/Parser/instantcheckmate.js',
            'path_to_deleter' => '',
        ],
//        [// not working, waiting for selector failed
//            'name' => 'intelius.com',
//            'path' => 'src/Parser/intelius.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'kwold.com',
            'path' => 'src/Parser/kwold.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'michiganresidentdatabase.com',
            'path' => 'src/Parser/michiganresidentdatabase.js',
            'path_to_deleter' => '',
        ],
//        [// not working, page https://www.mylife.com/ can't be loaded
//            'name' => 'mylife.com',
//            'path' => 'src/Parser/mylife.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'northcarolinaresidentdatabase.com',
            'path' => 'src/Parser/northcarolinaresidentdatabase.js',
            'path_to_deleter' => '',
        ],
//        [// cloudflare
//            'name' => 'nuwber.com',
//            'path' => 'src/Parser/nuwber.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'ohioresidentdatabase.com',
            'path' => 'src/Parser/ohioresidentdatabase.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'peekyou.com',
            'path' => 'src/Parser/peekyou.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'peopleFriends.com',
            'path' => 'src/Parser/peoplefinders.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'peoplewhiz.com',
            'path' => 'src/Parser/peoplewhiz.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'radaris.com',
            'path' => 'src/Parser/radaris.js',
            'path_to_deleter' => '',
        ],
//        [// not working, waiting for selector failed
//            'name' => 'searchquarry.com',
//            'path' => 'src/Parser/searchquarry.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'spokeo.com',
            'path' => 'src/Parser/spokeo.js',
            'path_to_deleter' => '',
        ],
//        [// cloudflare
//            'name' => 'truePeopleSearch.com',
//            'path' => 'src/Parser/truepeoplesearch.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'truthfinder.com',
            'path' => 'src/Parser/truthfinder.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'usaTrace.com',
            'path' => 'src/Parser/usatrace.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'usSearch.com',
            'path' => 'src/Parser/ussearch.js',
            'path_to_deleter' => '',
        ],
//        [// cloudflare
//            'name' => 'voterRecords.com',
//            'path' => 'src/Parser/voterrecords.js',
//            'path_to_deleter' => '',
//        ],
        [
            'name' => 'whitePages',
            'path' => 'src/Parser/whitepages.js',
            'path_to_deleter' => '',
        ],
        [
            'name' => 'zabasearch.com',
            'path' => 'src/Parser/zabasearch.js',
            'path_to_deleter' => '',
        ]
    ];
}
